openapi: 3.0.1
info:
  title: products
  description: Product operations
  version: v0
servers:
  - url: https://apis.vinmonopolet.no/products/v0
paths:
  /monthly-sales-per-store:
    get:
      summary: Get monthly sales
      description: "CHANGED FROM 15. MARCH 2021: Monthly sales available from the 35th day after a month.\nReturns monthly sales data. \n<br>\nMonthly sales available from the 35th day after a month, at approx 07:30 AM CET. Use parameter \"changedSince\" to get any updates / corrections made to historic sales. Select only one month to avoid pagination. If you experience timeouts, use pagination by sending parameter maxResults (default 1048575 ).\n<br>\nThrottling as per 19. August 2021: Max 6 calls per minute. Max 60 calls per day."
      operationId: GET_MONTHLY_SALES
      parameters:
        - name: fromSalesMonth
          in: query
          description: Returns sales occurrences in interval from this sales month yyyy-MM
          schema:
            type: string
        - name: toSalesMonth
          in: query
          description: Returns sales occurrences in interval to this sales month yyyy-MM
          schema:
            type: string
        - name: fromStoreId
          in: query
          description: Returns sales occurrences in interval from this store id number
          schema:
            type: integer
        - name: toStoreId
          in: query
          description: Returns sales occurrences in interval to this store id number
          schema:
            type: integer
        - name: productId
          in: query
          description: Returns sales occurrences for requested productId
          schema:
            type: integer
        - name: vendorId
          in: query
          description: Returns sales occurrences for requested vendorId
          schema:
            type: integer
        - name: wholesalerId
          in: query
          description: Returns sales occurrences for requested wholesalerId
          schema:
            type: integer
        - name: changedSince
          in: query
          description: Returns sales occurrences that have been updated since the supplied month - only yyyy-MM-dd
          schema:
            type: string
        - name: maxResults
          in: query
          description: Limits the maximum number of sales occurrences returned in each request
          schema:
            type: integer
        - name: start
          in: query
          description: 'Skips the supplied amount of sales occurrences, ordered by sales month, store and productId'
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GET_MONTHLY_SALES_Response'
              example:
                - salesMonth: string
                  storeSales:
                    - storeId: string
                      sales:
                        - productId: string
                          salesVolume: 0
                          salesQuantity: 0
                          lastChanged:
                            date: string
                            time: string
        '400':
          description: Bad Request (wrong parameters/values supplied)
        '500':
          description: Error
    head:
      summary: Get monthly sales (no response body)
      description: "CHANGED FROM 15. MARCH 2021: Monthly sales available from the 35th day after a month.\nReturns monthly sales data. \n<br>\n(Same as Get method, but no response body, only header info)\n<br>\nMonthly sales available from the 35th day after a month, at approx 07:30 AM CET. Use parameter \"changedSince\" to get any updates / corrections made to historic sales. Select only one month to avoid pagination. If you experience timeouts, use pagination by sending parameter maxResults (default 1048575 ).\n<br>\nThrottling as per 19. August 2021: Max 6 calls per minute. Max 60 calls per day."
      operationId: 5e9d657fc1dd661604a972a4
      parameters:
        - name: fromSalesMonth
          in: query
          description: Returns sales occurrences in interval from this sales month yyyy-MM
          schema:
            type: string
        - name: toSalesMonth
          in: query
          description: Returns sales occurrences in interval to this sales month yyyy-MM
          schema:
            type: string
        - name: fromStoreId
          in: query
          description: Returns sales occurrences in interval from this store id number
          schema:
            type: integer
        - name: toStoreId
          in: query
          description: Returns sales occurrences in interval to this store id number
          schema:
            type: integer
        - name: productId
          in: query
          description: Returns sales occurrences for requested productId
          schema:
            type: integer
        - name: vendorId
          in: query
          description: Returns sales occurrences for requested vendorId
          schema:
            type: integer
        - name: wholesalerId
          in: query
          description: Returns sales occurrences for requested wholesalerId
          schema:
            type: integer
        - name: changedSince
          in: query
          description: Returns sales occurrences that have been updated since the supplied month - only yyyy-MM-dd
          schema:
            type: string
        - name: maxResults
          in: query
          description: Limits the maximum number of sales occurrences returned in each request
          schema:
            type: integer
        - name: start
          in: query
          description: 'Skips the supplied amount of sales occurrences, ordered by sales month, store and productId'
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GET_MONTHLY_SALES_Response'
              example:
                - salesMonth: string
                  storeSales:
                    - storeId: string
                      sales:
                        - productId: string
                          salesVolume: 0
                          salesQuantity: 0
                          lastChanged:
                            date: string
                            time: string
        '400':
          description: Bad Request (wrong parameters/values supplied)
        '500':
          description: Error
  /details-normal:
    get:
      summary: Get details-normal
      description: "CHANGED JSON RESPONSE FROM 10. APRIL 2021!\nReturns master data details on Vinmonopolet's products in basic, one lot, test and ordering ranges. <br>\nMaster data is updated approx 05:45 AM CET every day. Use parameter \"changedSince\" to get only updated products, including products that have been removed from basic, one lot, test and ordering ranges since supplied date.\n<br>\nThrottling as per 15. November 2019: Max 60 calls per minute. Max 4000 calls per day."
      operationId: GET_DETAILS_NORMAL
      parameters:
        - name: productId
          in: query
          description: Returns details of all products that match productId
          schema:
            type: string
        - name: vendorId
          in: query
          description: Returns details of all products that match vendorId
          schema:
            type: integer
        - name: manufacturerId
          in: query
          description: Returns details of all products that match manufacturerId
          schema:
            type: integer
        - name: wholesalerId
          in: query
          description: Returns details of all products that match wholesalerId
          schema:
            type: integer
        - name: changedSince
          in: query
          description: Returns details of all products that have been updated since the supplied date - only numeric yyyy-MM-dd
          schema:
            type: string
        - name: productShortNameContains
          in: query
          description: Returns details of all products where productShortName contains the supplied string
          schema:
            type: string
        - name: maxResults
          in: query
          description: Limits the maximum number of products returned in each request
          schema:
            type: integer
        - name: start
          in: query
          description: 'Skips the supplied amount of products, ordered by productID'
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GET_DETAILS_Response'
              example:
                - basic:
                    productId: string
                    productShortName: string
                  lastChanged:
                    date: string
                    time: string
        '400':
          description: Bad Request (wrong parameter values given)
        '500':
          description: Error
    head:
      summary: Get details-normal (no response body)
      description: "CHANGED JSON RESPONSE FROM 10. APRIL 2021!\nReturns master data details on Vinmonopolet's products in basic, one lot, test and ordering ranges. \n<br>\n(Same as Get method, but no response body, only header info)\n<br>\nMaster data is updated approx 05:45 AM CET every day. Use parameter \"changedSince\" to get only updated products, including products that have been removed from basic, one lot, test and ordering ranges since supplied date.\n<br>\nThrottling as per 15. November 2019: Max 60 calls per minute. Max 4000 calls per day."
      operationId: 5e9d65cd0b839fb90114d801
      parameters:
        - name: productId
          in: query
          description: Returns details of all products that match productId
          schema:
            type: string
        - name: vendorId
          in: query
          description: Returns details of all products that match vendorId
          schema:
            type: integer
        - name: manufacturerId
          in: query
          description: Returns details of all products that match manufacturerId
          schema:
            type: integer
        - name: wholesalerId
          in: query
          description: Returns details of all products that match wholesalerId
          schema:
            type: integer
        - name: changedSince
          in: query
          description: Returns details of all products that have been updated since the supplied date - only numeric yyyy-MM-dd
          schema:
            type: string
        - name: productShortNameContains
          in: query
          description: Returns details of all products where productShortName contains the supplied string
          schema:
            type: string
        - name: maxResults
          in: query
          description: Limits the maximum number of products returned in each request
          schema:
            type: integer
        - name: start
          in: query
          description: 'Skips the supplied amount of products, ordered by productID'
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GET_DETAILS_Response'
              example:
                - basic:
                    productId: string
                    productShortName: string
                  lastChanged:
                    date: string
                    time: string
        '400':
          description: Bad Request (wrong parameter values given)
        '500':
          description: Error
components:
  schemas:
    GET_DETAILS_Response:
      type: array
      items:
        properties:
          basic:
            type: object
            properties:
              productId:
                type: string
                description: Product ID
              productShortName:
                type: string
                description: Product short name
          lastChanged:
            type: object
            properties:
              date:
                type: string
                description: Date when product was last changed
              time:
                type: string
                description: Time when product was last changed
    GET_PRICE_CONDITIONS_Response:
      type: array
      items:
        type: object
        properties:
          productId:
            type: string
            description: Product ID
          priceElements:
            type: array
            items:
              type: object
              properties:
                salesPrice:
                  type: number
                  description: Sales price in NOK
                markup:
                  type: number
                  description: Markup in NOK
                dduPrice:
                  type: number
                  description: DDU Price in NOK
                salesPricePrLiter:
                  type: number
                  description: Sales price per liter in NOK
                valueAddedTax:
                  type: number
                  description: VAT in NOK
                alcoholTax:
                  type: number
                  description: Alcohol tax in NOK
                ecoTax:
                  type: number
                  description: Environmental tax in NOK
                packagingTax:
                  type: number
                  description: Packaging tax in NOK
                bottleReturnValue:
                  type: number
                  description: Bottle return value in NOK
    GET_MONTHLY_SALES_Response:
      type: array
      items:
        type: object
        properties:
          salesMonth:
            type: string
            description: Sales month in format yyyy-MM
          storeSales:
            type: array
            items:
              type: object
              properties:
                storeId:
                  type: string
                  description: Store ID
                sales:
                  type: array
                  items:
                    type: object
                    properties:
                      productId:
                        type: string
                        description: Product ID
                      salesVolume:
                        type: number
                        description: 'Sales volume in liters, with three decimals'
                      salesQuantity:
                        type: number
                        description: Sales volume in number of items
                      lastChanged:
                        type: object
                        properties:
                          date:
                            type: string
                            description: Date when product sales last changed
                          time:
                            type: string
                            description: Time when product sales last changed
    GET_STOCK_ACCUMULATED_Response:
      type: array
      items:
        type: object
        properties:
          productId:
            type: string
            description: Product ID
          stock:
            type: integer
            description: Accumulated stock in all stores (units)
          numberOfStoresWithStock:
            type: integer
            description: Total number of stores that have the product in stock
          updatedDate:
            type: string
            description: Last updated date
          updatedTime:
            type: string
            description: Last updated time
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]